server:
  port: 8082

spring:
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USER:guest}
    password: ${RABBITMQ_PASS:guest}
  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:noreply@eventplatform.com}
    password: ${MAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: ${MAIL_STARTTLS_ENABLE:true}
          ssl:
            enable: ${MAIL_SSL_ENABLE:false}

app:
  mail:
    from: ${MAIL_FROM:noreply@eventplatform.com}
